version: "3.4"

services:
  weaviate:
    image: semitechnologies/weaviate:1.26.2  # ✅ latest stable
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - ENABLE_MODULES=text2vec-openai
      - DEFAULT_VECTORIZER_MODULE=text2vec-openai
      - OPENAI_APIKEY=${OPENAI_API_KEY}
    volumes:
      - ./weaviate-data:/var/lib/weaviate

  scheduler:
    build: .
    depends_on:
      - weaviate
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "app.scheduler.scheduler"]
      interval: 1m
      timeout: 10s
      retries: 3
